### ISSUE TITLE
Option to fold first long comment too

### ISSUE THREAD

**Issue by mrx23dot** [ietxaniz/vscode-fold-ninja#3]
Comments can be

/*  */  multiline
/**  */ multiline
// many lines like this
///  many lines like this

test cases from Eclipse

**Comment by ietxaniz** [comment]
This is not golang only. Comments are supported as long as vscode treats them as comments. There are some examples in different languages in https://github.com/ietxaniz/vscode-fold-ninja-testproject. I tested them and it works.

**Comment by ietxaniz** [comment]
I think this issue can be closed. Please provide an example and explain what is happening if issue not solved.

**Comment by ietxaniz** [comment]
Yes, I think it is possible. This mode could have an icon like **{.1.}**.

**Comment by ietxaniz** [comment]
Hi mrx23dot,

I'm pleased to inform you that the "Fold First" feature you suggested has been implemented in the latest update of Fold Ninja. This mode, represented by the icon `{.1.}`, is designed to automatically collapse the first foldable block in a file, which is often a lengthy legal comment or similar content.

Currently, this feature is available for C, C++, C#, Go, Rust, JavaScript, TypeScript, and Python. I will implement automated tests to test that each language is processed correctly. These tests will be implemented as errors are found and adding the error to the test scenario. Should you encounter any bugs, please open an issue with an example file, detailing the current behavior and expected outcome.

Additionally, if there's a need to add support for another language, feel free to open a new issue with details about the language and an example file for reference.

**Comment by ietxaniz** [comment]
Thank you for your feedback. I'd like to clarify that Fold Ninja only stores settings and the working mode persistently, and there's no persistent storage of other data like file states.

I've recently released version 0.4.0 of Fold Ninja, which includes a complete rewrite of the extension with different algorithms. This update might address the issues you've encountered. I encourage you to update to this latest version and see if it resolves your concerns. If you still encounter problems, please feel free to open a new issue with detailed information including the source file and a description of the behavior you're observing.

**Comment by mrx23dot** [comment]
In  v0.4.1, intermediate still jumps to top everytime I change tabs.

![image](https://github.com/ietxaniz/vscode-fold-ninja/assets/4163396/0932c365-6166-4e2d-bb0f-6ebd5c558551)

**Comment by ietxaniz** [comment]
First and foremost, I would like to extend my sincere apologies for the inconvenience you've experienced with the Fold Ninja extension. Your feedback has been invaluable in identifying areas where improvements are necessary.

In response to the issues you've raised, as well as others I've identified, I am undertaking the following actions:

1. **Managing Document Folding Updates with Timestamps:** I'm opening issue #7 to enhance the way document folding updates are managed. Transitioning from using hashes to timestamps should improve functionality and resolve some of the existing problems.

2. **Implementing First Comment Block Folding and Document Parsing:** I recognize the importance of accurately folding the first comment block. To achieve this, I need to parse the document. Folding all block comments was simpler since Visual Studio Code already provides this functionality. The development and testing of the parser for Golang will be my starting point. Once implemented, I will update the documentation and subsequently expand this feature to other languages.

3. **New Feature Request Template:** To streamline future feature requests and ensure effective implementation, I'm introducing a new template for feature requests (issue #8). Additionally, for specific requests like the implementation of a parser for a language, a dedicated template will be provided. This approach is intended to facilitate more structured and efficient feature additions.
